"""The benchmark: does the harness reach the right verdict, and does it let good
work through.

Two numbers are reported and neither one alone is meaningful.

  Guard accuracy — over the whole golden set, how often the verdict matched the
  one the case says is correct. A suite that blocks everything scores 0.55 here,
  not 1.00, because the answerable cases count.

  False-block rate — of the questions that SHOULD have been allowed, how many
  were refused. This is the number that decides whether anyone keeps using the
  tool, and it is reported first for that reason.

Precision and recall are reported over the blocking decision, treating BLOCK as
the positive class: precision is how many blocks were deserved, recall is how
many of the deserved blocks happened. A missed block is a leak; a wrong block is
an obstacle. They are different failures and are counted separately.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field

from . import golden
from .guards import ALLOW, APPROVE, BLOCK, WARN, review
from .policy import READ_ONLY_ANALYST, Policy
from .providers import MockProvider

BLOCKING = {BLOCK}
PERMISSIVE = {ALLOW, WARN, APPROVE}


@dataclass
class CaseResult:
    case_id: str
    kind: str
    question: str
    sql: str
    expected: str
    actual: str
    correct: bool
    expected_guards: list = field(default_factory=list)
    fired_guards: list = field(default_factory=list)
    missing_guards: list = field(default_factory=list)
    failure: str = ""              # "" | false_block | missed_block | wrong_verdict

    def to_dict(self) -> dict:
        return asdict(self)


def _classify(expected: str, actual: str) -> str:
    if expected == actual:
        return ""
    if expected in PERMISSIVE and actual in BLOCKING:
        return "false_block"
    if expected in BLOCKING and actual in PERMISSIVE:
        return "missed_block"
    return "wrong_verdict"


def run_case(case, pol: Policy, provider=None, use_reference: bool = True) -> CaseResult:
    """Review one golden case.

    With `use_reference` the reference SQL is reviewed directly, which measures
    the guards. With a provider, the model generates from the question (starting
    from the reference so the mock's SQL-writing ability is not what is being
    scored) and the pipeline as a whole is measured.
    """
    sql = case.sql
    if provider is not None and not use_reference:
        sql = provider.generate(case.question, gold=case.sql or None)
    r = review(case.question, sql, pol)
    fired = [f.guard_id for f in r.findings]
    missing = [g for g in case.expect_guards if g not in fired]
    correct = r.verdict == case.expect_verdict
    return CaseResult(
        case_id=case.id, kind=case.kind, question=case.question, sql=sql,
        expected=case.expect_verdict, actual=r.verdict, correct=correct,
        expected_guards=list(case.expect_guards), fired_guards=fired,
        missing_guards=missing, failure=_classify(case.expect_verdict, r.verdict))


def run_benchmark(pol: Policy | None = None, provider=None,
                  use_reference: bool = True, cases=None) -> dict:
    """Score the whole set. Deterministic: same inputs, same numbers."""
    pol = pol or READ_ONLY_ANALYST
    cases = cases if cases is not None else golden.CASES
    results = [run_case(c, pol, provider, use_reference) for c in cases]

    total = len(results)
    correct = sum(1 for r in results if r.correct)
    should_allow = [r for r in results if r.expected in PERMISSIVE]
    should_block = [r for r in results if r.expected in BLOCKING]

    false_blocks = [r for r in results if r.failure == "false_block"]
    missed_blocks = [r for r in results if r.failure == "missed_block"]
    wrong = [r for r in results if r.failure == "wrong_verdict"]

    tp = sum(1 for r in should_block if r.actual in BLOCKING)
    fp = len(false_blocks)
    fn = len(missed_blocks)
    precision = tp / (tp + fp) if (tp + fp) else 1.0
    recall = tp / (tp + fn) if (tp + fn) else 1.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0

    missing_guards = {}
    for r in results:
        for g in r.missing_guards:
            missing_guards.setdefault(g, []).append(r.case_id)

    return {
        "mode": "reference SQL" if use_reference else f"generated by {getattr(provider, 'name', '?')}",
        "policy": pol.name,
        "cost_usd": 0.0 if provider is None or getattr(provider, "name", "") == "mock" else None,
        "cases": total,
        "by_kind": golden.counts(),
        "guard_accuracy": round(correct / total, 4) if total else 0.0,
        "false_block_rate": round(len(false_blocks) / len(should_allow), 4) if should_allow else 0.0,
        "missed_block_rate": round(len(missed_blocks) / len(should_block), 4) if should_block else 0.0,
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "false_blocks": [r.case_id for r in false_blocks],
        "missed_blocks": [r.case_id for r in missed_blocks],
        "wrong_verdict": [r.case_id for r in wrong],
        "expected_guards_that_did_not_fire": missing_guards,
        "per_case": [r.to_dict() for r in results],
    }


def summary_lines(result: dict) -> list:
    """The numbers as sentences, in the order that matters."""
    return [
        f"Golden set: {result['cases']} cases "
        f"({result['by_kind'].get('ANSWERABLE', 0)} answerable, "
        f"{result['by_kind'].get('GUARDED', 0)} guarded, "
        f"{result['by_kind'].get('HOSTILE', 0)} hostile), "
        f"policy {result['policy']}, SQL from {result['mode']}.",
        f"False blocks: {result['false_block_rate']:.1%} of the questions that should "
        f"have been allowed were refused"
        + (f" ({', '.join(result['false_blocks'])})" if result["false_blocks"] else ""),
        f"Missed blocks: {result['missed_block_rate']:.1%} of the questions that should "
        f"have been refused got through"
        + (f" ({', '.join(result['missed_blocks'])})" if result["missed_blocks"] else ""),
        f"Verdict accuracy {result['guard_accuracy']:.1%}; "
        f"precision {result['precision']:.3f}, recall {result['recall']:.3f}, "
        f"F1 {result['f1']:.3f} over the blocking decision.",
        "Every number here is measured against a golden set the author wrote and can "
        "defend. It says nothing about queries outside that set.",
    ]


def fault_curve(pol: Policy | None = None, rates=(0.0, 0.25, 0.5, 0.75, 1.0)) -> list:
    """How the harness behaves as the model gets worse.

    The interesting property of a guard suite is not how it scores against a
    good model, it is whether it degrades gracefully against a bad one.
    """
    out = []
    for rate in rates:
        provider = MockProvider(fault_rate=rate, seed=7)
        r = run_benchmark(pol, provider=provider, use_reference=False)
        out.append({"fault_rate": rate, "guard_accuracy": r["guard_accuracy"],
                    "false_block_rate": r["false_block_rate"],
                    "missed_block_rate": r["missed_block_rate"],
                    "blocked": sum(1 for c in r["per_case"] if c["actual"] == BLOCK)})
    return out
